/*
 * ApprovalFormOfferPage.java
 *
 * Created on September 2, 2013, 5:31 PM
 */

package com.rameses.clfc.loan;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;
import java.math.BigDecimal;

/**
 *
 * @author  Rameses
 */
@Template(FormPage.class)
public class ApprovalOfferFormPage extends javax.swing.JPanel {
    
    /** Creates new form ApprovalFormOfferPage */
    public ApprovalOfferFormPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xButton1 = new com.rameses.rcp.control.XButton();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        jPanel4.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Offer Information");
        jPanel4.setBorder(xTitledBorder1);
        jPanel6.setLayout(null);

        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(xLineBorder1);
        jPanel6.setOpaque(false);

        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xNumberField1.setCaption("Applied Amount");
        xNumberField1.setCaptionWidth(110);
        xNumberField1.setEnabled(false);
        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setName("loanamount");
        xNumberField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel2.add(xNumberField1);

        xNumberField2.setCaption("Approved Amount");
        xNumberField2.setCaptionWidth(110);
        xNumberField2.setFieldType(BigDecimal.class);
        xNumberField2.setName("entity.amountapproved");
        xNumberField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField2.setRequired(true);
        xFormPanel2.add(xNumberField2);

        xNumberField3.setCaption("Credit Limit");
        xNumberField3.setCaptionWidth(110);
        xNumberField3.setFieldType(BigDecimal.class);
        xNumberField3.setName("entity.creditlimit");
        xNumberField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField3.setRequired(true);
        xFormPanel2.add(xNumberField3);

        jPanel6.add(xFormPanel2);
        xFormPanel2.setBounds(10, 10, 240, 70);

        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel3.setPadding(new java.awt.Insets(3, 0, 0, 0));
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Absences");
        xComboBox1.setCaptionWidth(110);
        xComboBox1.setExpression("#{item.value}");
        xComboBox1.setItemKey("value");
        xComboBox1.setItems("absenceTypes");
        xComboBox1.setName("entity.absences");
        xComboBox1.setPreferredSize(new java.awt.Dimension(130, 19));
        xComboBox1.setRequired(true);
        xFormPanel3.add(xComboBox1);

        xNumberField5.setFieldType(Integer.class);
        xNumberField5.setName("entity.policy");
        xNumberField5.setPreferredSize(new java.awt.Dimension(50, 19));
        xNumberField5.setShowCaption(false);
        xFormPanel3.add(xNumberField5);

        xNumberField6.setFieldType(Integer.class);
        xNumberField6.setName("entity.provisions");
        xNumberField6.setPreferredSize(new java.awt.Dimension(50, 19));
        xNumberField6.setShowCaption(false);
        xFormPanel3.add(xNumberField6);

        jPanel6.add(xFormPanel3);
        xFormPanel3.setBounds(10, 70, 380, 30);

        xFormPanel4.setPadding(new java.awt.Insets(4, 0, 0, 0));
        xNumberField4.setCaption("Gradual Increase");
        xNumberField4.setCaptionWidth(110);
        xNumberField4.setFieldType(BigDecimal.class);
        xNumberField4.setName("entity.increase");
        xNumberField4.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel4.add(xNumberField4);

        jPanel6.add(xFormPanel4);
        xFormPanel4.setBounds(10, 90, 240, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(10, 30, 470, 120);

        xFormPanel5.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel5.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xLabel1.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel1.setShowCaption(false);
        xLabel1.setText("Must/Required Collateral(s)");
        xFormPanel5.add(xLabel1);

        xSeparator1.setPreferredSize(new java.awt.Dimension(700, 19));
        javax.swing.GroupLayout xSeparator1Layout = new javax.swing.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        xFormPanel5.add(xSeparator1);

        jPanel4.add(xFormPanel5);
        xFormPanel5.setBounds(10, 160, 470, 30);

        xDataTable1.setColumns(new com.rameses.rcp.common.Column[]{
            new com.rameses.rcp.common.Column(new Object[]{
                new Object[]{"name", "description"}
                , new Object[]{"caption", "Description"}
                , new Object[]{"width", 100}
                , new Object[]{"minWidth", 0}
                , new Object[]{"maxWidth", 0}
                , new Object[]{"required", false}
                , new Object[]{"resizable", true}
                , new Object[]{"nullWhenEmpty", true}
                , new Object[]{"editable", false}
                , new Object[]{"textCase", com.rameses.rcp.constant.TextCase.UPPER}
                , new Object[]{"typeHandler", new com.rameses.rcp.common.TextColumnHandler()}
            })
        });
        xDataTable1.setHandler("mustCollateralHandler");
        xDataTable1.setName("selectedMustCollateral");
        jPanel4.add(xDataTable1);
        xDataTable1.setBounds(10, 180, 470, 90);

        xButton1.setText("Add");
        jPanel4.add(xButton1);
        xButton1.setBounds(10, 280, 77, 23);

        xFormPanel6.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel6.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xLabel2.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel2.setPreferredSize(new java.awt.Dimension(41, 19));
        xLabel2.setShowCaption(false);
        xLabel2.setText("Remarks");
        xFormPanel6.add(xLabel2);

        xSeparator2.setPreferredSize(new java.awt.Dimension(700, 19));
        javax.swing.GroupLayout xSeparator2Layout = new javax.swing.GroupLayout(xSeparator2);
        xSeparator2.setLayout(xSeparator2Layout);
        xSeparator2Layout.setHorizontalGroup(
            xSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        xSeparator2Layout.setVerticalGroup(
            xSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        xFormPanel6.add(xSeparator2);

        jPanel4.add(xFormPanel6);
        xFormPanel6.setBounds(10, 310, 470, 30);

        jPanel5.setLayout(new java.awt.BorderLayout());

        xTextArea1.setName("entity.remarks");
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 330, 470, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
