/*
 * BussinessFormPage2.java
 *
 * Created on September 2, 2013, 10:48 AM
 */

package com.rameses.clfc.loan;

/**
 *
 * @author  Rameses
 */
public class BussinessFormPage extends javax.swing.JPanel {
    
    /** Creates new form BussinessFormPage2 */
    public BussinessFormPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();

        jPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Business Information");
        jPanel1.setBorder(xTitledBorder1);

        xFormPanel1.setPadding(new java.awt.Insets(2, 0, 0, 0));
        xTextField1.setText("xTextField1");
        xTextField1.setCaption("Firm/Trade Name");
        xTextField1.setCaptionWidth(100);
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xTextField1);

        xTextField2.setText("xTextField2");
        xTextField2.setCaption("Address");
        xTextField2.setCaptionWidth(100);
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xTextField2);

        jPanel1.add(xFormPanel1);
        xFormPanel1.setBounds(10, 20, 580, 50);

        xFormPanel2.setPadding(new java.awt.Insets(4, 5, 0, 0));
        xComboBox1.setCaption("Kind of Business");
        xComboBox1.setCaptionWidth(150);
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel2.add(xComboBox1);

        xTextField3.setText("xTextField3");
        xTextField3.setCaption("Stall Size/P.O. Size(in mtrs.)");
        xTextField3.setCaptionWidth(150);
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel2.add(xTextField3);

        xTextField6.setText("xTextField4");
        xTextField6.setCaption("Estimated Daily Sales");
        xTextField6.setCaptionWidth(150);
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel2.add(xTextField6);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 42));
        xTextArea2.setCaption("Business Hours");
        xTextArea2.setCaptionWidth(150);
        xTextArea2.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane2.setViewportView(xTextArea2);

        xFormPanel2.add(jScrollPane2);

        xTextField5.setText("xTextField5");
        xTextField5.setCaption("Tel. No.");
        xTextField5.setCaptionWidth(150);
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel2.add(xTextField5);

        jPanel1.add(xFormPanel2);
        xFormPanel2.setBounds(290, 60, 300, 130);

        xFormPanel3.setPadding(new java.awt.Insets(4, 0, 0, 0));
        xComboBox2.setCaption("Occupancy");
        xComboBox2.setCaptionWidth(100);
        xComboBox2.setPreferredSize(new java.awt.Dimension(120, 19));
        xFormPanel3.add(xComboBox2);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 40));
        xTextArea1.setCaption("Remarks");
        xTextArea1.setCaptionWidth(100);
        xTextArea1.setPreferredSize(new java.awt.Dimension(100, 38));
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel3.add(jScrollPane1);

        jPanel1.add(xFormPanel3);
        xFormPanel3.setBounds(10, 60, 280, 70);

        xFormPanel4.setPadding(new java.awt.Insets(7, 0, 0, 0));
        xDateField1.setText("xDateField1");
        xDateField1.setCaption("Business Started");
        xDateField1.setCaptionWidth(100);
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel4.add(xDateField1);

        xNumberField1.setText("xNumberField1");
        xNumberField1.setCaption("Initial Invested");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setPreferredSize(new java.awt.Dimension(130, 19));
        xFormPanel4.add(xNumberField1);

        xComboBox3.setCaption("Ownership");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setPreferredSize(new java.awt.Dimension(120, 19));
        xFormPanel4.add(xComboBox3);

        jPanel1.add(xFormPanel4);
        xFormPanel4.setBounds(10, 120, 280, 70);

        xFormPanel6.setPadding(new java.awt.Insets(0, 5, 0, 0));
        jPanel1.add(xFormPanel6);
        xFormPanel6.setBounds(30, 230, 260, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    // End of variables declaration//GEN-END:variables
    
}
