/*
 * EmploymentForm.java
 *
 * Created on September 2, 2013, 11:14 AM
 */

package com.rameses.clfc.loan;

/**
 *
 * @author  Rameses
 */
public class EmploymentFormPage extends javax.swing.JPanel {
    
    /** Creates new form EmploymentForm */
    public EmploymentFormPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Employment Information");
        xFormPanel1.setBorder(xTitledBorder1);
        xTextField1.setText("xTextField1");
        xTextField1.setCaption("Employer");
        xTextField1.setCaptionWidth(100);
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xTextField2.setText("xTextField2");
        xTextField2.setCaption("Tel. No.");
        xTextField2.setCaptionWidth(100);
        xTextField2.setPreferredSize(new java.awt.Dimension(100, 19));
        xFormPanel1.add(xTextField2);

        xTextField3.setText("xTextField3");
        xTextField3.setCaption("Address");
        xTextField3.setCaptionWidth(100);
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xTextField3);

        xTextField4.setText("xTextField4");
        xTextField4.setCaption("Position");
        xTextField4.setCaptionWidth(100);
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xTextField4);

        xNumberField1.setText("xNumberField1");
        xNumberField1.setCaption("Salary");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setPreferredSize(new java.awt.Dimension(130, 19));
        xFormPanel1.add(xNumberField1);

        xTextField5.setText("xTextField5");
        xTextField5.setCaption("Length of Service");
        xTextField5.setCaptionWidth(100);
        xTextField5.setPreferredSize(new java.awt.Dimension(130, 19));
        xFormPanel1.add(xTextField5);

        xComboBox1.setCaption("Status");
        xComboBox1.setCaptionWidth(100);
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        xFormPanel1.add(xComboBox1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 80));
        xTextArea1.setCaption("Remarks");
        xTextArea1.setCaptionWidth(100);
        xTextArea1.setRequired(true);
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
    
}
