/*
 * LoanAppDetailPage.java
 *
 * Created on September 10, 2013, 5:45 PM
 */

package com.rameses.clfc.loan;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  wflores
 */
@StyleSheet
public class LoanAppDetailPage extends javax.swing.JPanel 
{    
    public LoanAppDetailPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xLabel3 = new com.rameses.rcp.control.XLabel();
        jPanel1 = new javax.swing.JPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        jPanel2 = new javax.swing.JPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();

        com.rameses.rcp.control.border.XEtchedBorder xEtchedBorder1 = new com.rameses.rcp.control.border.XEtchedBorder();
        xEtchedBorder1.setHideLeft(true);
        xEtchedBorder1.setHideRight(true);
        xEtchedBorder1.setHideTop(true);
        xLabel3.setBorder(xEtchedBorder1);
        xLabel3.setFontStyle("font-weight:bold;");
        xLabel3.setForeground(new java.awt.Color(80, 80, 80));
        xLabel3.setText("Loan Details");

        xFormPanel2.setCellspacing(4);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel2.setBorder(xLineBorder1);
        xLabel2.setCaption("App Type");
        xLabel2.setCaptionWidth(110);
        xLabel2.setExpression("#{entity.apptype}");
        xLabel2.setPreferredSize(new java.awt.Dimension(150, 18));
        xFormPanel2.add(xLabel2);

        xComboBox3.setAllowNull(false);
        xComboBox3.setCaption("Client Type");
        xComboBox3.setCaptionWidth(110);
        xComboBox3.setExpression("#{item.value}");
        xComboBox3.setItemKey("value");
        xComboBox3.setItems("clientTypes");
        xComboBox3.setName("entity.clienttype");
        xComboBox3.setPreferredSize(new java.awt.Dimension(150, 19));
        xComboBox3.setRequired(true);
        xFormPanel2.add(xComboBox3);

        xComboBox4.setCaption("Product Type");
        xComboBox4.setCaptionWidth(110);
        xComboBox4.setDepends(new String[] {"entity"});
        xComboBox4.setDynamic(true);
        xComboBox4.setExpression("#{item.name}");
        xComboBox4.setImmediate(true);
        xComboBox4.setItems("productTypes");
        xComboBox4.setName("schedule");
        xComboBox4.setPreferredSize(new java.awt.Dimension(150, 19));
        xComboBox4.setRequired(true);
        xFormPanel2.add(xComboBox4);

        xNumberField2.setCaption("Amount Applied");
        xNumberField2.setCaptionWidth(110);
        xNumberField2.setName("entity.loanamount");
        xNumberField2.setRequired(true);
        xFormPanel2.add(xNumberField2);

        xFormPanel1.setCellspacing(4);
        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));
        com.rameses.rcp.control.border.XLineBorder xLineBorder2 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder2.setLineColor(new java.awt.Color(204, 204, 204));
        xDateField1.setBorder(xLineBorder2);
        xDateField1.setCaption("Date Filed");
        xDateField1.setCaptionWidth(100);
        xDateField1.setName("entity.dtcreated");
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xDateField1.setReadonly(true);
        xFormPanel1.add(xDateField1);

        com.rameses.rcp.control.border.XLineBorder xLineBorder3 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder3.setLineColor(new java.awt.Color(204, 204, 204));
        xLabel1.setBorder(xLineBorder3);
        xLabel1.setCaption("Interviewed By");
        xLabel1.setCaptionWidth(100);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 19));
        xFormPanel1.add(xLabel1);

        xNumberField1.setCaption("Term");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setDepends(new String[] {"loanapp.schedule"});
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("entity.schedule.term");
        xNumberField1.setRequired(true);
        xFormPanel1.add(xNumberField1);

        xNumberField3.setText("xNumberField3");
        xNumberField3.setCaption("Loan Count");
        xNumberField3.setCaptionWidth(100);
        xNumberField3.setFieldType(Integer.class);
        xNumberField3.setPreferredSize(new java.awt.Dimension(100, 19));
        xNumberField3.setReadonly(true);
        xFormPanel1.add(xNumberField3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xFormPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
            .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );

        xFormPanel3.setCellspacing(4);
        xFormPanel3.setPadding(new java.awt.Insets(3, 0, 0, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 80));
        xTextArea1.setCaption("Purpose of Loan");
        xTextArea1.setCaptionWidth(110);
        xTextArea1.setName("entity.purpose");
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel3.add(jScrollPane1);

        xLookupField1.setCaption("Route");
        xLookupField1.setCaptionWidth(110);
        xLookupField1.setDepends(new String[] {"entity"});
        xLookupField1.setExpression("#{item.code} - #{item.description} #{item.area}");
        xLookupField1.setHandler("routeLookupHandler");
        xLookupField1.setName("entity.route");
        xLookupField1.setPreferredSize(new java.awt.Dimension(250, 20));
        xFormPanel3.add(xLookupField1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xFormPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(xLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(xLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
