/*
 * ProductTypePage.java
 *
 * Created on September 6, 2013, 11:48 AM
 */

package com.rameses.clfc.loan;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;
import java.math.BigDecimal;

/**
 *
 * @author  Rameses
 */
@Template(FormPage.class)
public class ProductTypePage extends javax.swing.JPanel {
    
    /** Creates new form ProductTypePage */
    public ProductTypePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Product Type Information");
        xFormPanel1.setBorder(xTitledBorder1);
        xTextField1.setCaption("Name");
        xTextField1.setCaptionWidth(135);
        xTextField1.setName("entity.name");
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("Description");
        xTextField2.setCaptionWidth(135);
        xTextField2.setName("entity.description");
        xTextField2.setPreferredSize(new java.awt.Dimension(250, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xNumberField1.setCaption("Term");
        xNumberField1.setCaptionWidth(135);
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("entity.term");
        xNumberField1.setRequired(true);
        xFormPanel1.add(xNumberField1);

        xNumberField2.setCaption("Interest Rate");
        xNumberField2.setCaptionWidth(135);
        xNumberField2.setFieldType(BigDecimal.class);
        xNumberField2.setName("entity.interestrate");
        xNumberField2.setRequired(true);
        xFormPanel1.add(xNumberField2);

        xNumberField3.setCaption("Past Due Rate");
        xNumberField3.setCaptionWidth(135);
        xNumberField3.setFieldType(BigDecimal.class);
        xNumberField3.setName("entity.pastduerate");
        xNumberField3.setRequired(true);
        xFormPanel1.add(xNumberField3);

        xNumberField4.setCaption("Underpayment Penalty");
        xNumberField4.setCaptionWidth(135);
        xNumberField4.setFieldType(BigDecimal.class);
        xNumberField4.setName("entity.underpaymentpenalty");
        xNumberField4.setRequired(true);
        xFormPanel1.add(xNumberField4);

        xNumberField5.setCaption("Surcharge Rate");
        xNumberField5.setCaptionWidth(135);
        xNumberField5.setFieldType(BigDecimal.class);
        xNumberField5.setName("entity.surchargerate");
        xNumberField5.setRequired(true);
        xFormPanel1.add(xNumberField5);

        xNumberField6.setCaption("Absent Penalty");
        xNumberField6.setCaptionWidth(135);
        xNumberField6.setFieldType(BigDecimal.class);
        xNumberField6.setName("entity.absentpenalty");
        xNumberField6.setRequired(true);
        xFormPanel1.add(xNumberField6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
    
}
