/*
 * ProductTypePage.java
 *
 * Created on September 6, 2013, 11:48 AM
 */

package com.rameses.clfc.loan;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;
import java.math.BigDecimal;

/**
 *
 * @author  Rameses
 */
@Template(FormPage.class)
public class ProductTypePage extends javax.swing.JPanel {
    
    /** Creates new form ProductTypePage */
    public ProductTypePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField3 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField4 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField5 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField6 = new com.rameses.rcp.control.XDecimalField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Product Type Information");
        xFormPanel1.setBorder(xTitledBorder1);
        xTextField1.setCaption("Name");
        xTextField1.setCaptionWidth(135);
        xTextField1.setName("entity.name");
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("Description");
        xTextField2.setCaptionWidth(135);
        xTextField2.setName("entity.description");
        xTextField2.setPreferredSize(new java.awt.Dimension(250, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xDecimalField1.setCaption("Term");
        xDecimalField1.setCaptionWidth(135);
        xDecimalField1.setName("entity.term");
        xDecimalField1.setPattern("#,##0");
        xDecimalField1.setRequired(true);
        xDecimalField1.setScale(0);
        xFormPanel1.add(xDecimalField1);

        xDecimalField2.setCaption("Interest Rate");
        xDecimalField2.setCaptionWidth(135);
        xDecimalField2.setName("entity.interestrate");
        xDecimalField2.setRequired(true);
        xFormPanel1.add(xDecimalField2);

        xDecimalField3.setCaption("Past Due Rate");
        xDecimalField3.setCaptionWidth(135);
        xDecimalField3.setName("entity.pastduerate");
        xDecimalField3.setRequired(true);
        xFormPanel1.add(xDecimalField3);

        xDecimalField4.setCaption("Underpayment Penalty");
        xDecimalField4.setCaptionWidth(135);
        xDecimalField4.setName("entity.underpaymentpenalty");
        xDecimalField4.setRequired(true);
        xFormPanel1.add(xDecimalField4);

        xDecimalField5.setCaption("Surcharge Rate");
        xDecimalField5.setCaptionWidth(135);
        xDecimalField5.setName("entity.surchargerate");
        xDecimalField5.setRequired(true);
        xFormPanel1.add(xDecimalField5);

        xDecimalField6.setCaption("Absent Penalty");
        xDecimalField6.setCaptionWidth(135);
        xDecimalField6.setName("entity.absentpenalty");
        xDecimalField6.setRequired(true);
        xFormPanel1.add(xDecimalField6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField3;
    private com.rameses.rcp.control.XDecimalField xDecimalField4;
    private com.rameses.rcp.control.XDecimalField xDecimalField5;
    private com.rameses.rcp.control.XDecimalField xDecimalField6;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
    
}
