/*
 * RealPropertyFormPage.java
 *
 * Created on September 2, 2013, 11:57 AM
 */

package com.rameses.clfc.loan;

import java.math.BigDecimal;

/**
 *
 * @author  Rameses
 */
public class RealPropertyFormPage extends javax.swing.JPanel {
    
    /** Creates new form RealPropertyFormPage */
    public RealPropertyFormPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();

        jPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Real Property Information");
        jPanel1.setBorder(xTitledBorder1);

        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(2, 0, 0, 0));
        xNumberField1.setText("xNumberField1");
        xNumberField1.setCaption("Area");
        xNumberField1.setCaptionWidth(140);
        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setPreferredSize(new java.awt.Dimension(100, 19));
        xNumberField1.setRequired(true);
        xFormPanel2.add(xNumberField1);

        xComboBox2.setPreferredSize(new java.awt.Dimension(50, 19));
        xComboBox2.setRequired(true);
        xComboBox2.setShowCaption(false);
        xFormPanel2.add(xComboBox2);

        jPanel1.add(xFormPanel2);
        xFormPanel2.setBounds(10, 60, 340, 30);

        xFormPanel3.setPadding(new java.awt.Insets(3, 0, 0, 0));
        xTextField2.setText("xTextField2");
        xTextField2.setCaption("Zonal Value");
        xTextField2.setCaptionWidth(140);
        xTextField2.setPreferredSize(new java.awt.Dimension(100, 19));
        xTextField2.setRequired(true);
        xFormPanel3.add(xTextField2);

        xDateField1.setText("xDateField1");
        xDateField1.setCaption("Date Acquired");
        xDateField1.setCaptionWidth(140);
        xDateField1.setPreferredSize(new java.awt.Dimension(100, 19));
        xFormPanel3.add(xDateField1);

        xTextField3.setText("xTextField3");
        xTextField3.setCaption("Acquired From");
        xTextField3.setCaptionWidth(140);
        xTextField3.setPreferredSize(new java.awt.Dimension(160, 19));
        xTextField3.setRequired(true);
        xFormPanel3.add(xTextField3);

        xComboBox3.setCaption("Mode of Acquisition");
        xComboBox3.setCaptionWidth(140);
        xComboBox3.setPreferredSize(new java.awt.Dimension(150, 19));
        xComboBox3.setRequired(true);
        xFormPanel3.add(xComboBox3);

        xNumberField2.setText("xNumberField2");
        xNumberField2.setCaption("Market/Appraisal Value");
        xNumberField2.setCaptionWidth(140);
        xNumberField2.setFieldType(BigDecimal.class);
        xNumberField2.setPreferredSize(new java.awt.Dimension(120, 19));
        xNumberField2.setRequired(true);
        xFormPanel3.add(xNumberField2);

        xTextField4.setText("xTextField4");
        xTextField4.setCaption("Reigstered Name");
        xTextField4.setCaptionWidth(140);
        xTextField4.setPreferredSize(new java.awt.Dimension(160, 19));
        xTextField4.setRequired(true);
        xFormPanel3.add(xTextField4);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 80));
        xTextArea1.setCaption("Remarks");
        xTextArea1.setCaptionWidth(140);
        xTextArea1.setRequired(true);
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel3.add(jScrollPane1);

        jPanel1.add(xFormPanel3);
        xFormPanel3.setBounds(10, 80, 380, 220);

        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xComboBox1.setCaption("Classification");
        xComboBox1.setCaptionWidth(140);
        xComboBox1.setPreferredSize(new java.awt.Dimension(120, 19));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xTextField1.setText("xTextField1");
        xTextField1.setCaption("Location");
        xTextField1.setCaptionWidth(140);
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        jPanel1.add(xFormPanel1);
        xFormPanel1.setBounds(10, 20, 380, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    // End of variables declaration//GEN-END:variables
    
}
