/*
 * SubmitForApprovalPage.java
 *
 * Created on September 2, 2013, 2:24 PM
 */

package com.rameses.clfc.loan;

import java.math.BigDecimal;

/**
 *
 * @author  Rameses
 */
public class SubmitForApprovalPage extends javax.swing.JPanel {
    
    /** Creates new form SubmitForApprovalPage */
    public SubmitForApprovalPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xSeparator1 = new com.rameses.rcp.control.XSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xSeparator2 = new com.rameses.rcp.control.XSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        xNumberField7 = new com.rameses.rcp.control.XNumberField();
        xNumberField8 = new com.rameses.rcp.control.XNumberField();

        jPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Submit For Approval");
        jPanel1.setBorder(xTitledBorder1);

        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xLabel1.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel1.setPreferredSize(new java.awt.Dimension(88, 19));
        xLabel1.setShowCaption(false);
        xLabel1.setText("Recommendations");
        xFormPanel1.add(xLabel1);

        xSeparator1.setPreferredSize(new java.awt.Dimension(700, 19));
        javax.swing.GroupLayout xSeparator1Layout = new javax.swing.GroupLayout(xSeparator1);
        xSeparator1.setLayout(xSeparator1Layout);
        xSeparator1Layout.setHorizontalGroup(
            xSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        xSeparator1Layout.setVerticalGroup(
            xSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        xFormPanel1.add(xSeparator1);

        jPanel1.add(xFormPanel1);
        xFormPanel1.setBounds(10, 30, 360, 40);

        jPanel2.setLayout(new java.awt.BorderLayout());

        xTextArea1.setRequired(true);
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 360, 70);

        xFormPanel2.setCellpadding(new java.awt.Insets(0, 0, 0, 5));
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xNumberField4.setText("xNumberField4");
        xNumberField4.setCaption("CAO");
        xNumberField4.setCaptionWidth(50);
        xNumberField4.setFieldType(BigDecimal.class);
        xNumberField4.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField4.setRequired(true);
        xFormPanel2.add(xNumberField4);

        xNumberField5.setText("xNumberField5");
        xNumberField5.setCaption("BCOH");
        xNumberField5.setCaptionWidth(50);
        xNumberField5.setFieldType(BigDecimal.class);
        xNumberField5.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField5.setRequired(true);
        xFormPanel2.add(xNumberField5);

        jPanel1.add(xFormPanel2);
        xFormPanel2.setBounds(200, 130, 170, 60);

        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel3.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xLabel2.setPadding(new java.awt.Insets(1, 0, 1, 0));
        xLabel2.setPreferredSize(new java.awt.Dimension(185, 19));
        xLabel2.setShowCaption(false);
        xLabel2.setText("Remarks for submitting this application");
        xFormPanel3.add(xLabel2);

        xSeparator2.setPreferredSize(new java.awt.Dimension(700, 19));
        javax.swing.GroupLayout xSeparator2Layout = new javax.swing.GroupLayout(xSeparator2);
        xSeparator2.setLayout(xSeparator2Layout);
        xSeparator2Layout.setHorizontalGroup(
            xSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        xSeparator2Layout.setVerticalGroup(
            xSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        xFormPanel3.add(xSeparator2);

        jPanel1.add(xFormPanel3);
        xFormPanel3.setBounds(10, 210, 360, 40);

        jPanel3.setLayout(new java.awt.BorderLayout());

        xTextArea2.setRequired(true);
        xTextArea2.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane2.setViewportView(xTextArea2);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 230, 360, 80);

        xFormPanel4.setCellpadding(new java.awt.Insets(0, 0, 0, 5));
        xFormPanel4.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xNumberField6.setText("xNumberField1");
        xNumberField6.setCaption("Marketer");
        xNumberField6.setCaptionWidth(70);
        xNumberField6.setFieldType(BigDecimal.class);
        xNumberField6.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField6.setRequired(true);
        xFormPanel4.add(xNumberField6);

        xNumberField7.setText("xNumberField2");
        xNumberField7.setCaption("CI");
        xNumberField7.setCaptionWidth(70);
        xNumberField7.setFieldType(BigDecimal.class);
        xNumberField7.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField7.setRequired(true);
        xFormPanel4.add(xNumberField7);

        xNumberField8.setText("xNumberField3");
        xNumberField8.setCaption("FCA");
        xNumberField8.setCaptionWidth(70);
        xNumberField8.setFieldType(BigDecimal.class);
        xNumberField8.setPreferredSize(new java.awt.Dimension(0, 19));
        xNumberField8.setRequired(true);
        xFormPanel4.add(xNumberField8);

        jPanel1.add(xFormPanel4);
        xFormPanel4.setBounds(10, 130, 180, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XNumberField xNumberField7;
    private com.rameses.rcp.control.XNumberField xNumberField8;
    private com.rameses.rcp.control.XSeparator xSeparator1;
    private com.rameses.rcp.control.XSeparator xSeparator2;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    // End of variables declaration//GEN-END:variables
    
}
